### ISSUE TITLE
Red Black Tree Specifciation too restrictive?

### ISSUE THREAD

**Issue by Pat-Lafon** [zhezhouzz/underapproximation_type#35]
I was consulting with QuickChick on RedBlack Tree generators and noticed that they have an additional case: https://github.com/QuickChick/QuickChick/blob/235f6f2156b06239d10e971b7f229f18b73fb67c/examples/RedBlack/testing.v#L167-L168

I believe this part of the specification is too restrictive? https://github.com/zhezhouzz/underapproximation_type/blob/1657dd90dee11544fdfcb699a8c9e02c09d2d1ab/data/benchmark/quickchick/rbtree/_under.ml#L17

**Comment by zhezhouzz** [comment]
You are right, it is too restrictive, it can be a red (true) root, or just leaf.
I have fixed it in `meta` branch, `data/validation/rbtree.ml`.
It would be merged into main branch soon.
